#' Accept/reject helper
#'
#' Determines whether \eqn{H_0}: OR = \code{.odds_ratio} is accepted for the
#' observed table \eqn{z = (u, t = u + v)}. First finds the optimal
#' \eqn{\gamma_0} via \code{optimise_gamma0()}, then evaluates the MFET
#' rejection indicator via \code{.modified_reject()}. Returns 1 (accept) or
#' 0 (reject). Used in the bisection searches for confidence limits and
#' p-values in \code{modified_fisher_exact_test()}, and not exported.
#'
#' @param z Length-2 integer vector \eqn{(u, t)}, where \eqn{u} is the
#'   observed number of successes in group 1 and \eqn{t = u + v} is the total
#'   number of successes.
#' @param .odds_ratio The null hypothesis odds ratio \eqn{\theta_0}. No default.
#' @param .m Number of trials in group 1.
#' @param .n Number of trials in group 2.
#' @param .df Test frame (data frame) generated by \code{construct_test_frame()},
#'   containing critical values \eqn{c_1}, \eqn{c_2} and randomisation
#'   probabilities \eqn{\gamma_1}, \eqn{\gamma_2} for every possible total \eqn{T}.
#' @param .alpha Nominal significance level \eqn{\alpha}. No default.
#' @param .precision Numerical precision for p-values, confidence limits, and
#'   size calculations. No default.
#' @param .method Numerical method for maximising the local size over the
#'   nuisance parameter. Either \code{"zoom"} (default in the main function) or
#'   \code{"trust"} (uses the trust-region method from the trust package).
#' @param .maze Number of grid points evaluated at each zoom iteration.
#' @param .zoom_iter Number of zoom iterations (\code{"zoom"} method only).
#'
#' @noRd
.accept <- function(z, .odds_ratio, .m, .n, .df, .alpha, .precision,
                   .method, .maze, .zoom_iter){

  gamma0 <- optimise_gamma0(.odds_ratio, .m, .n, .alpha, .precision,
                            .method, .maze, .zoom_iter)

  accept <- 1 - .modified_reject(z, .df, gamma0)

  return(accept)

}
