#' Helper to construct rejection matrix of the MFET
#'
#' Builds the \eqn{(m+1) \times (n+1)} matrix of MFET rejection indicators
#' for a given test frame and \eqn{\gamma_0} threshold. Entry \eqn{[i+1, j+1]}
#' is 1 if the MFET rejects the table with \eqn{u = i} successes in group 1 and
#' \eqn{v = j} successes in group 2 (total \eqn{t = i + j}), and 0 otherwise,
#' replicating the five-branch logic of \code{.mfet_reject()} — including the
#' combined \eqn{\gamma_1 + \gamma_2 > \gamma_0} rule when \eqn{c_1 = c_2} —
#' in vectorised form.
#'
#' Because the rejection decision depends only on the test frame and
#' \eqn{\gamma_0}, and not on the nuisance parameter \eqn{p_0}, this matrix can
#' be built once and reused across every nuisance-parameter evaluation: the
#' local size then reduces to the bilinear form
#' \eqn{p_u^\top R \, p_v}, where \eqn{p_u} and \eqn{p_v} are the binomial
#' probability vectors of the two groups. \code{size_mfet()} exploits this by
#' constructing the matrix once per \eqn{\gamma_0} and passing it to
#' \code{local_size_mfet()} for every point on the zoom grid.
#'
#' @param .df Test frame (data frame) generated by \code{construct_test_frame()},
#'   containing critical values \eqn{c_1}, \eqn{c_2} and randomisation
#'   probabilities \eqn{\gamma_1}, \eqn{\gamma_2} for every possible total \eqn{T}.
#' @param .gamma0 The \eqn{\gamma_0} threshold: boundary values in the test
#'   frame are rejected only when their randomisation probability exceeds this
#'   value. Typically the output of \code{optimise_gamma0()}.
#' @param .m Number of trials in group 1.
#' @param .n Number of trials in group 2.
#'
#' @return A numeric matrix with \eqn{m + 1} rows and \eqn{n + 1} columns of
#'   0/1 rejection indicators, with rows indexing \eqn{u = 0, \ldots, m} and
#'   columns indexing \eqn{v = 0, \ldots, n}.
#'
#' @noRd
.build_rejection_matrix <- function(.df, .gamma0, .m, .n){

  c1 <- as.numeric(.df$c1); c2 <- as.numeric(.df$c2)
  g1 <- as.numeric(.df$gamma1); g2 <- as.numeric(.df$gamma2)

  S   <- matrix(0:.m, nrow = .m+1, ncol = .n+1)
  idx <- outer(0:.m, 0:.n, `+`) + 1L

  C1 <- matrix(c1[idx], nrow = .m+1); C2 <- matrix(c2[idx], nrow = .m+1)
  G1 <- matrix(g1[idx], nrow = .m+1); G2 <- matrix(g2[idx], nrow = .m+1)

  # Strictly outside [c1, c2]: always reject
  R <- (S < C1) | (S > C2)

  # Boundary cases (mirrors .mfet_reject(), including the c1 == c2 override):
  eq  <- C1 == C2
  at1 <- (S == C1) & !eq
  at2 <- (S == C2) & !eq
  atb <- (S == C1) & eq

  R[at1] <- G1[at1] > .gamma0
  R[at2] <- G2[at2] > .gamma0
  R[atb] <- (G1[atb] + G2[atb]) > .gamma0

  storage.mode(R) <- "double"

  return(R)

}
