#' Local size gradient of the MFET
#'
#' Computes the first derivative of the local size with respect to the nuisance
#' parameter \eqn{p_0}, using the analytic derivative of the binomial PMF.
#' Used by \code{size_modified()} when \code{method = "trust"} to supply the
#' gradient to the trust-region optimiser.
#'
#' @param nuisance The nuisance parameter \eqn{p_0}: success probability in
#'   group 1 under \eqn{H_0}. Must be in \eqn{[0, 1]}.
#' @param .gamma0 The \eqn{\gamma_0} threshold: boundary values in the test
#'   frame are rejected only when their randomisation probability exceeds this
#'   value. Typically the output of \code{optimise_gamma0()}.
#' @param .m Number of trials in group 1.
#' @param .n Number of trials in group 2.
#' @param .df Test frame (data frame) generated by \code{construct_test_frame()},
#'   containing critical values \eqn{c_1}, \eqn{c_2} and randomisation
#'   probabilities \eqn{\gamma_1}, \eqn{\gamma_2} for every possible total \eqn{T}.
#' @param .odds_ratio The null hypothesis odds ratio \eqn{\theta_0}. No default.
#' @param .alpha Nominal significance level \eqn{\alpha}. No default.
#' @param .precision Numerical precision. No default.
#'
#' @noRd
.local_size_gradient_modified <- function(nuisance, .gamma0, .odds_ratio, .m, .n,
                                      .df, .alpha, .precision){

  p0 <- nuisance[[1]]
  p1 <- p0/(p0 + .odds_ratio*(1-p0))

  locsizegrad <- 0
  dp1dp0 <- .odds_ratio/(p0+.odds_ratio*(1-p0))^2

  for(i in 0:.m){

    for(j in 0:.n){

      x <- c(i, i+j)

      if(i == 0){ term1 <- -.m*(1-p0)^(.m-1) }
      if(i == .m){ term1 <- .m*p0^(.m-1) }

      if(i > 0 & i < .m){
        # x = r of successes, prob, size = number of trials
        term1 <- stats::dbinom(x = i-1, prob = p0, size = .m-2)*.m*(.m-1)/
          (i*(.m-i))*(i-.m*p0)

      }

      if(j == 0){ term2 <- -.n*(1-p1)^(.n-1) }
      if(j == .n){ term2 <- .n*p1^(.n-1) }

      if(j > 0 & j < .n){
        term2 <- stats::dbinom(x = j-1, prob = p1, size = .n-2)*.n*(.n-1)/
          (j*(.n-j))*(j-.n*p1)
      }

      total <- term1*stats::dbinom(x = j, prob = p1, size = .n) +
        term2*stats::dbinom(x = i, prob = p0, size = .m)*dp1dp0

      locsizegrad <- locsizegrad + .modified_reject(x, .df, .gamma0)*total

    }

  }

  return(locsizegrad)

}

## Create second derivative (Hessian) for use in trust method -----------------

# local_size_hessian <- function(nuisance, .gamma0, .odds_ratio, .m, .n,
#                                .df, .alpha, .precision){
#
#   p0 <- nuisance[[1]]
#   p1 <- p0/(p0 + .odds_ratio*(1-p0))
#
#   locsizehessian <- 0
#
#   d2p0_d2p1
#   d2p1_d2p0
#
#   d2p0_dp1dp0
#   d2p0_dp0dp1
#
#   d2p1_dp1dp0
#   d2p1_dp0dp1
#
#   for(i in 0:.m){
#
#     for(j in 0:.n){
#
#       x <- c(i, i+j)
#
#       if(i == 0){ term1 <- -.m*(1-p0)^(.m-1) }
#       if(i == .m){ term1 <- .m*p0^(.m-1) }
#
#       if(i > 0 & i < .m){
#         # x = r of successes, prob, size = number of trials
#         term1 <- dbinom(x = i-1, prob = p0, size = .m-2)*.m*(.m-1)/
#           (i*(.m-i))*(i-.m*p0)
#
#       }
#
#       if(j == 0){ term2 <- -.n*(1-p1)^(.n-1) }
#       if(j == .n){ term2 <- .n*p1^(.n-1) }
#
#       if(j > 0 & j < .n){
#         term2 <- dbinom(x = j-1, prob = p1, size = .n-2)*.n*(.n-1)/
#           (j*(.n-j))*(j-.n*p1)
#       }
#
#       total <- term1*dbinom(x = j, prob = p1, size = .n) +
#         term2*dbinom(x = i, prob = p0, size = .m)*dp1dp0
#
#       locsizehessian <- locsizehessian + .modified_reject(x, .df, .gamma0)*total
#
#     }
#
#   }
#
#   return(locsizehessian)
#
# }
