#' Local size of the randomised (UMPU) Fisher exact test
#'
#' Computes the unconditional rejection probability (local size) of the fully
#' randomised UMPU Fisher exact test at nuisance parameter \eqn{p_0}, where
#' \eqn{p_1 = p_0 / (p_0 + \theta_0 (1 - p_0))}. Unlike \code{local_size_modified()},
#' which applies a \eqn{\gamma_0} threshold and returns 0 or 1 at the boundary,
#' this function uses \eqn{\gamma_1} and \eqn{\gamma_2} directly as rejection
#' probabilities, reflecting the true expected size of the randomised test.
#'
#' @param nuisance The nuisance parameter \eqn{p_0}: success probability in
#'   group 1 under \eqn{H_0}. Must be in \eqn{[0, 1]}.
#' @param .m Number of trials in group 1.
#' @param .n Number of trials in group 2.
#' @param .df Test frame (data frame) generated by \code{construct_test_frame()},
#'   containing critical values \eqn{c_1}, \eqn{c_2} and randomisation
#'   probabilities \eqn{\gamma_1}, \eqn{\gamma_2} for every possible total \eqn{T}.
#' @param .odds_ratio The null hypothesis odds ratio \eqn{\theta_0}. No default.
#' @param .alpha Nominal significance level \eqn{\alpha}. No default.
#' @param .precision Numerical precision. No default.
#'
#' @return A single numeric value: the local size of the randomised UMPU Fisher
#'   exact test at the given nuisance parameter, in \eqn{[0, 1]}.
#' @examples
#' df <- construct_test_frame(.odds_ratio = 1, .m = 6, .n = 4,
#'                            .alpha = 0.05, .precision = 1e-3)
#' local_size_randomised(nuisance = 0.5, .m = 6, .n = 4, .df = df,
#'                       .odds_ratio = 1, .alpha = 0.05, .precision = 1e-3)
#' @export
#' @keywords internal
#' @family size
local_size_randomised <- function(nuisance, .m, .n, .df, .odds_ratio,
                                  .alpha, .precision) {

  p0 <- min(max(0, nuisance), 1)
  p1 <- p0 / (p0 + .odds_ratio * (1 - p0))

  size <- 0

  for (i in 0:.m) {
    for (j in 0:.n) {

      t  <- i + j
      c1 <- .df$c1[[t + 1]]
      c2 <- .df$c2[[t + 1]]
      g1 <- .df$gamma1[[t + 1]]
      g2 <- .df$gamma2[[t + 1]]

      # Expected rejection probability for the randomised test
      if (i < c1 | i > c2) {

        phi <- 1                        # strictly outside: always reject

      } else if (c1 == c2 & i == c1) {

        phi <- g1 + g2                  # single boundary point

      } else if (i == c1) {

        phi <- g1                       # lower boundary: randomise with gamma1

      } else if (i == c2) {

        phi <- g2                       # upper boundary: randomise with gamma2

      } else {

        phi <- 0                        # strictly inside: never reject

      }

      size <- size +
        phi *
        stats::dbinom(i, size = .m, prob = p0) *
        stats::dbinom(j, size = .n, prob = p1)
    }
  }

  return(size)

}
