#' Local size of the MFET
#'
#' Computes the unconditional rejection probability (local size) of the MFET
#' at nuisance parameter \eqn{p_0}, where
#' \eqn{p_1 = p_0 / (p_0 + \theta_0 (1 - p_0))}. Called repeatedly by
#' \code{mfet_size()} during numerical optimisation over \eqn{p_0} to find
#' the maximum size.
#'
#' @param nuisance The nuisance parameter \eqn{p_0}: success probability in
#'   group 1 under \eqn{H_0}. Must be in \eqn{[0, 1]}.
#' @param .gamma0 The \eqn{\gamma_0} threshold: boundary values in the test
#'   frame are rejected only when their randomisation probability exceeds this
#'   value. Typically the output of \code{optimise_gamma0()}.
#' @param .m Number of trials in group 1.
#' @param .n Number of trials in group 2.
#' @param .df Test frame (data frame) generated by \code{construct_test_frame()},
#'   containing critical values \eqn{c_1}, \eqn{c_2} and randomisation
#'   probabilities \eqn{\gamma_1}, \eqn{\gamma_2} for every possible total \eqn{T}.
#' @param .odds_ratio The null hypothesis odds ratio \eqn{\theta_0}. No default.
#' @param .alpha Nominal significance level \eqn{\alpha}. No default.
#' @param .precision Numerical precision. No default.
#'
#' @keywords find local size hypothesis test gradient

local_size <- function(nuisance, .gamma0, .odds_ratio, .m, .n,
                       .df, .alpha, .precision){

  p0 <- min(max(0, nuisance[[1]]), 1)
  p1 <- p0/(p0 + .odds_ratio*(1-p0))

  locsize <- 0

  for(i in 0:.m){

    for(j in 0:.n){

      x <- c(i, i+j)

      locsize <- locsize + mod_fe_test(x, .df, .gamma0) *
        stats::dbinom(x = i, prob = p0, size = .m)*
        stats::dbinom(x = j, prob = p1, size = .n)

    }

  }

  return(locsize)

}
