
#' Power of the MFET
#'
#' Computes the unconditional power of the MFET at response rates
#' \eqn{(\pi_1, \pi_2)}, i.e. the probability of rejecting
#' \eqn{H_0}: OR = \eqn{\theta_0} when the true success probabilities are
#' \eqn{\pi_1} (group 1) and \eqn{\pi_2} (group 2). The test is defined by
#' the \eqn{\gamma_0} threshold and the test frame supplied. Optionally
#' restricts to the superiority sub-region where the observed rate in group 2
#' exceeds that in group 1.
#'
#' @param p Length-2 numeric vector \eqn{(\pi_1, \pi_2)}: success probability
#'   in group 1 (\eqn{\pi_1}) and group 2 (\eqn{\pi_2}) at which power is
#'   evaluated.
#' @param .gamma0 The \eqn{\gamma_0} threshold: boundary values in the test
#'   frame are rejected only when their randomisation probability exceeds this
#'   value. Typically the output of \code{optimise_gamma0()}.
#' @param .odds_ratio Null hypothesis odds ratio \eqn{\theta_0} used to build
#'   the test frame. The power is evaluated at the response rates \eqn{(\pi_1,
#'   \pi_2)} supplied in \code{p}, against this null.
#' @param .m Number of trials in group 1.
#' @param .n Number of trials in group 2.
#' @param .df Test frame (data frame) generated by \code{construct_test_frame()},
#'   containing critical values \eqn{c_1}, \eqn{c_2} and randomisation
#'   probabilities \eqn{\gamma_1}, \eqn{\gamma_2} for every possible total \eqn{T}.
#' @param .alpha Nominal significance level \eqn{\alpha}. No default.
#' @param .precision Numerical precision. No default.
#' @param .superiority Logical. If \code{TRUE}, power is computed only over
#'   tables where the observed rate in group 2 exceeds that in group 1.
#'   Defaults to \code{FALSE}.
#'
#' @keywords find power test

power_mfet <- function(p, .gamma0, .odds_ratio, .m, .n, .df, .alpha,
                       .precision, .superiority){

  p0 <- p[[1]]
  p1 <- p[[2]]

  z <- c(0, 0)

  power <- 0

  for(u in 0:.m){

    for(v in 0:.n){

      z <- c(u, u+v)

      if(.superiority == TRUE){

        power <- power + (v/.n > u/.m)*
          mod_fe_test(z, .df, .gamma0)*
          stats::dbinom(x = u, prob = p0, size = .m)*
          stats::dbinom(x = v, prob = p1, size = .n)

      } else {

        power <- power +
          mod_fe_test(z, .df, .gamma0)*
          stats::dbinom(x = u, prob = p0, size = .m)*
          stats::dbinom(x = v, prob = p1, size = .n)

      }

    }

  }

  return(power)

}
