#' Actual size of the MFET for a given \eqn{\gamma_0}
#'
#' Finds the actual size of the MFET for a given \eqn{\gamma_0} by numerically
#' maximising the local size over the nuisance parameter \eqn{p_0 \in (0, 1)}.
#' Supports two methods: \code{"zoom"} evaluates the local size at a grid of
#' points and iteratively refines the maximum (matches the SAS macro default);
#' \code{"trust"} uses a trust-region optimiser with the analytic gradient from
#' \code{local_size_gradient()}.
#'
#' @param .c The \eqn{\gamma_0} value for which the actual size is to be
#'   computed. Supplied as a length-1 list element; typically one element of
#'   the sorted randomisation probability vector from the test frame.
#' @param .odds_ratio The null hypothesis odds ratio \eqn{\theta_0}. No default.
#' @param .m Number of trials in group 1.
#' @param .n Number of trials in group 2.
#' @param .df Test frame (data frame) generated by \code{construct_test_frame()},
#'   containing critical values \eqn{c_1}, \eqn{c_2} and randomisation
#'   probabilities \eqn{\gamma_1}, \eqn{\gamma_2} for every possible total \eqn{T}.
#' @param .alpha Nominal significance level \eqn{\alpha}. No default.
#' @param .precision Numerical precision. No default.
#' @param .method Numerical method: \code{"zoom"} or \code{"trust"}.
#' @param .maze Number of grid points evaluated at each zoom iteration.
#' @param .zoom_iter Number of zoom iterations (\code{"zoom"} method only).
#'
#' @importFrom numDeriv hessian
#' @importFrom trust trust
#' @keywords find actual size modified fisher exact test trust zoom

mfet_size <- function(.c, .odds_ratio, .m, .n, .df, .alpha, .precision,
                      .method, .maze, .zoom_iter){

  if(.method == "trust"){

    size_old <- 0
    start <- 0

    gamma0 <- .c[[1]]

    for(i in 1:(.maze-1)){

      x0 <- i/.maze

      size_new <- local_size(x0, gamma0, .odds_ratio, .m, .n,
                             .df, .alpha, .precision)

      if(size_new > size_old){

        size_old <- size_new

        start <- x0

      }

    }

    # Define objective function that gives local size value, derivative,
    # and second derivative (Hessian):

    objfun <- function(x, ...){

      # Constrain x:
      if(x > 1 | x < 0) return(list(value = -Inf))

      # Size (value, and function):
      f <- local_size(nuisance = x, ...)
      fx <- function(x) local_size(nuisance = x, ...)

      # Derivative (value, and function):
      g <- local_size_gradient(nuisance = x, ...)
      gx <- function(x) local_size_gradient(nuisance = x, ...)

      # Hessian (= Jacobian of first deriv):
      #B <- numDeriv::jacobian(func = gx, x)

      # Hessian :
      B <- numDeriv::hessian(func = fx, x)

      return(list(value = f, gradient = g, hessian = B))

    }

    # Use this + the trust-region method to find the maximum size as a function
    # of the nuisance parameter:

    result <- trust::trust(function(x) objfun(x, .gamma0 = gamma0, .odds_ratio,
                                              .m, .n, .df, .alpha, .precision),
                           start, .precision, 1/.precision, minimize = FALSE)


    size <- result$value

    # SAS code has following, but not needed here - we get the
    # resulting value (size):

    #xopt <- result$value
    #size <- local_size(xopt, .gamma0 = gamma0, .odds_ratio,
    #                   .m, .n, .df, .alpha, .precision)

  } else {

    # Else, use the zoom method as per SAS macro:

    res <- rep(0, .maze-1)
    pt <- 0
    gamma0 <- .c[[1]]
    maxat <- 0.5

    for(j in 1:.zoom_iter){

      for(i in 1:(.maze-1)){

        pt <- maxat + (i-.maze/2)/(.maze^j)

        res[[i]] <- local_size(pt, .gamma0 = gamma0, .odds_ratio, .m, .n, .df,
                               .alpha, .precision)

      }

      i <- which.max(res)

      old <- maxat
      maxat <- old + (i-.maze/2)/(.maze^j)

    }

    size <- max(res)

  } # End of zoom method

  return(size)

} # End of function
