#' MFET rejection indicator
#'
#' Implements the modified Fisher exact test (MFET) rejection indicator for a
#' single observed table \eqn{(u, t = u + v)}. Returns 1 (reject) or 0
#' (accept). Values of \eqn{u} strictly outside \eqn{[c_1, c_2]} always
#' reject; values strictly inside always accept; boundary values
#' (\eqn{u = c_1} or \eqn{u = c_2}) reject only when the corresponding
#' randomisation probability (\eqn{\gamma_1} or \eqn{\gamma_2}) exceeds the
#' \eqn{\gamma_0} threshold. When \eqn{c_1 = c_2}, the combined probability
#' \eqn{\gamma_1 + \gamma_2} is compared against \eqn{\gamma_0}.
#'
#' @param z Length-2 integer vector \eqn{(u, t)}, where \eqn{u} is the
#'   observed number of successes in group 1 and \eqn{t = u + v} is the total
#'   number of successes.
#' @param .df Test frame (data frame) generated by \code{construct_test_frame()},
#'   containing critical values \eqn{c_1}, \eqn{c_2} and randomisation
#'   probabilities \eqn{\gamma_1}, \eqn{\gamma_2} for every possible total \eqn{T}.
#' @param .gamma0 The \eqn{\gamma_0} threshold: boundary values are rejected
#'   only when their randomisation probability exceeds this value. Typically
#'   the output of \code{optimise_gamma0()}.
#'
#' @noRd
.modified_reject <- function(z, .df, .gamma0){

  s <- z[[1]]
  i <- z[[2]]

  if(s > .df$c1[[i+1]] & s < .df$c2[[i+1]]){ opttest <- 0 }

  if(s == .df$c1[[i+1]]){ opttest <- as.numeric(.df$gamma1[[i+1]] > .gamma0) }
  if(s == .df$c2[[i+1]]){ opttest <- as.numeric(.df$gamma2[[i+1]] > .gamma0) }

  if(s < .df$c1[[i+1]] | s > .df$c2[[i+1]]){ opttest <- 1 }

  if(.df$c1[[i+1]] == .df$c2[[i+1]] & s == .df$c1[[i+1]]){
    opttest <- as.numeric((.df$gamma1[[i+1]]+.df$gamma2[[i+1]]) > .gamma0)
  }

  return(opttest)

}
