#' Power of the randomised (UMPU) Fisher exact test
#'
#' Computes the unconditional power of the fully randomised UMPU Fisher exact
#' test at response rates \eqn{(\pi_1, \pi_2)}. Uses \eqn{\gamma_1} and
#' \eqn{\gamma_2} from the test frame directly as rejection probabilities at
#' the boundary, rather than applying a \eqn{\gamma_0} threshold. The test
#' frame should be built for the relevant null odds ratio.
#'
#' @param p Length-2 numeric vector \eqn{(\pi_1, \pi_2)}: success probability
#'   in group 1 (\eqn{\pi_1}) and group 2 (\eqn{\pi_2}) at which power is
#'   evaluated.
#' @param .m Number of trials in group 1.
#' @param .n Number of trials in group 2.
#' @param .df Test frame (data frame) generated by \code{construct_test_frame()},
#'   containing critical values \eqn{c_1}, \eqn{c_2} and randomisation
#'   probabilities \eqn{\gamma_1}, \eqn{\gamma_2} for every possible total \eqn{T}.
#' @param .alpha Nominal significance level \eqn{\alpha}. No default.
#' @param .precision Numerical precision. No default.
#' @param .superiority Logical. If \code{TRUE}, power is computed only over
#'   tables where the observed rate in group 2 exceeds that in group 1.
#'   Defaults to \code{FALSE}.
#'
#' @return A single numeric value: the power of the randomised UMPU Fisher exact
#'   test at the response rates \eqn{(\pi_1, \pi_2)}, in \eqn{[0, 1]}.
#' @examples
#' df <- construct_test_frame(.odds_ratio = 1, .m = 6, .n = 4,
#'                            .alpha = 0.05, .precision = 1e-3)
#' power_randomised(p = c(0.2, 0.6), .m = 6, .n = 4, .df = df,
#'                  .alpha = 0.05, .precision = 1e-3)
#' @export
#' @keywords internal
#' @family power
power_randomised <- function(p, .m, .n, .df, .alpha, .precision,
                             .superiority = FALSE) {

  p0 <- p[[1]]
  p1 <- p[[2]]
  power <- 0

  for (u in 0:.m) {
    for (v in 0:.n) {

      t  <- u + v
      c1 <- .df$c1[[t + 1]]
      c2 <- .df$c2[[t + 1]]
      g1 <- .df$gamma1[[t + 1]]
      g2 <- .df$gamma2[[t + 1]]

      if (u < c1 | u > c2) {
        phi <- 1
      } else if (c1 == c2 & u == c1) {
        phi <- g1 + g2
      } else if (u == c1) {
        phi <- g1
      } else if (u == c2) {
        phi <- g2
      } else {
        phi <- 0
      }

      contribution <- phi *
        stats::dbinom(u, size = .m, prob = p0) *
        stats::dbinom(v, size = .n, prob = p1)

      if (.superiority) {
        power <- power + (v / .n > u / .m) * contribution
      } else {
        power <- power + contribution
      }
    }
  }

  return(power)

}
