#' Power of the conservative Fisher exact test
#'
#' Computes the unconditional power of the conservative (non-randomised) Fisher
#' exact test at response rates \eqn{(\pi_1, \pi_2)}. Rejects \eqn{H_0} only
#' when \eqn{S} falls strictly outside the critical region \eqn{[c_1, c_2]},
#' equivalent to setting \eqn{\gamma_0 = 1} in the MFET so that boundary
#' values are never rejected. The test frame should be built for the relevant
#' null odds ratio.
#'
#' @param p Length-2 numeric vector \eqn{(\pi_1, \pi_2)}: success probability
#'   in group 1 (\eqn{\pi_1}) and group 2 (\eqn{\pi_2}) at which power is
#'   evaluated.
#' @param .m Number of trials in group 1.
#' @param .n Number of trials in group 2.
#' @param .df Test frame (data frame) generated by \code{construct_test_frame()},
#'   containing critical values \eqn{c_1}, \eqn{c_2} and randomisation
#'   probabilities \eqn{\gamma_1}, \eqn{\gamma_2} for every possible total \eqn{T}.
#' @param .alpha Nominal significance level \eqn{\alpha}. No default.
#' @param .precision Numerical precision. No default.
#' @param .superiority Logical. If \code{TRUE}, power is computed only over
#'   tables where the observed rate in group 2 exceeds that in group 1.
#'   Defaults to \code{FALSE}.
#'
#' @keywords find power test

power_conservative <- function(p, .m, .n, .df, .alpha, .precision,
                               .superiority = FALSE) {

  p0 <- p[[1]]
  p1 <- p[[2]]
  power <- 0

  for (u in 0:.m) {
    for (v in 0:.n) {
      z <- c(u, u + v)

      # gamma0 = 1 means reject only when strictly outside [c1, c2]
      reject <- mod_fe_test(z, .df, .gamma0 = 1)

      contribution <- reject *
        stats::dbinom(u, size = .m, prob = p0) *
        stats::dbinom(v, size = .n, prob = p1)

      if (.superiority) {
        power <- power + (v / .n > u / .m) * contribution
      } else {
        power <- power + contribution
      }
    }
  }

  return(power)

}
