#' Randomised (UMPU) Fisher exact test — work in progress
#'
#' Intended to implement the fully randomised UMPU Fisher exact test, in which
#' boundary values \eqn{u = c_1} and \eqn{u = c_2} are rejected with
#' probability \eqn{\gamma_1} and \eqn{\gamma_2} respectively. Boundary
#' randomisation is not yet implemented (those lines are commented out) and the
#' function currently behaves as the conservative test. Use
#' \code{local_size_randomised()} for size calculations and
#' \code{power_randomised()} for power calculations involving the fully
#' randomised test.
#'
#' @param z Length-2 integer vector \eqn{(u, t)}, where \eqn{u} is the
#'   observed number of successes in group 1 and \eqn{t = u + v} is the total
#'   number of successes.
#' @param .df Test frame (data frame) generated by \code{construct_test_frame()},
#'   containing critical values \eqn{c_1}, \eqn{c_2} and randomisation
#'   probabilities \eqn{\gamma_1}, \eqn{\gamma_2} for every possible total \eqn{T}.
#'
#' @noRd
random_fe_test <- function(z, .df){

  # WIP!!

  randtest <- NULL

  s <- z[[1]]
  i <- z[[2]]

  if(s > .df$c1[[i+1]] & s < .df$c2[[i+1]]){ randtest <- 0 }

  #if(s == .df$c1[[i+1]]){ randtest <- .df$gamma1[[i+1]] > .gamma0}
  #if(s == .df$c2[[i+1]]){ randtest <- .df$gamma2[[i+1]] > .gamma0}

  if(s < .df$c1[[i+1]] | s > .df$c2[[i+1]]){ randtest <- 1 }

  #if(.df$c1[[i+1]] == .df$c2[[i+1]] & s == .df$c1[[i+1]]){
  #  randtest <- (.df$gamma1[[i+1]]+.df$gamma2[[i+1]]) > .gamma0
  #}

  return(randtest)

}
