#' Actual size of the MFET for a given \eqn{\gamma_0}
#'
#' Finds the actual size of the MFET for a given \eqn{\gamma_0} by numerically
#' maximising the local size over the nuisance parameter \eqn{p_0 \in (0, 1)}.
#' Supports two methods: \code{"zoom"} evaluates the local size at a grid of
#' points and iteratively refines the maximum (matches the SAS macro default);
#' \code{"trust"} uses a trust-region optimiser with the analytic gradient from
#' \code{.local_size_gradient_modified()}.
#'
#' @param .c The \eqn{\gamma_0} value for which the actual size is to be
#'   computed. Supplied as a length-1 list element; typically one element of
#'   the sorted randomisation probability vector from the test frame.
#' @param .odds_ratio The null hypothesis odds ratio \eqn{\theta_0}. No default.
#' @param .m Number of trials in group 1.
#' @param .n Number of trials in group 2.
#' @param .df Test frame (data frame) generated by \code{construct_test_frame()},
#'   containing critical values \eqn{c_1}, \eqn{c_2} and randomisation
#'   probabilities \eqn{\gamma_1}, \eqn{\gamma_2} for every possible total \eqn{T}.
#' @param .alpha Nominal significance level \eqn{\alpha}. No default.
#' @param .precision Numerical precision. No default.
#' @param .method Numerical method: \code{"zoom"} or \code{"trust"}.
#' @param .maze Number of grid points evaluated at each zoom iteration.
#' @param .zoom_iter Number of zoom iterations (\code{"zoom"} method only).
#'
#' @importFrom numDeriv hessian
#' @importFrom trust trust
#' @return A single numeric value: the actual size of the test, i.e. the local
#'   size maximised over the nuisance parameter, in \eqn{[0, 1]}.
#' @examples
#' df <- construct_test_frame(.odds_ratio = 1, .m = 6, .n = 4,
#'                            .alpha = 0.05, .precision = 1e-3)
#' # Actual size of the test at a candidate gamma0 threshold of 0.05:
#' size_modified(.c = 0.05, .odds_ratio = 1, .m = 6, .n = 4, .df = df,
#'           .alpha = 0.05, .precision = 1e-3, .method = "zoom",
#'           .maze = 10, .zoom_iter = 6)
#' @export
#' @family modified
#' @family size
#' @seealso [optimise_gamma0()] which maximises this quantity to find the optimal gamma0; [local_size_modified()] for the local size at a fixed nuisance parameter value, of which this is the maximum; [local_size_asymptotic()], [local_size_probability()], [local_size_randomised()] for the equivalent quantity under alternative tests.
size_modified <- function(.c, .odds_ratio, .m, .n, .df, .alpha, .precision,
                      .method, .maze, .zoom_iter){

  if(.method == "trust"){

    size_old <- 0
    start <- 0

    gamma0 <- .c[[1]]

    for(i in 1:(.maze-1)){

      x0 <- i/.maze

      size_new <- local_size_modified(x0, gamma0, .odds_ratio, .m, .n,
                                  .df, .alpha, .precision)

      if(size_new > size_old){

        size_old <- size_new

        start <- x0

      }

    }

    # Define objective function that gives local size value, derivative,
    # and second derivative (Hessian):

    objfun <- function(x, ...){

      # Constrain x:
      if(x > 1 | x < 0) return(list(value = -Inf))

      # Size (value, and function):
      f <- local_size_modified(nuisance = x, ...)
      fx <- function(x) local_size_modified(nuisance = x, ...)

      # Derivative (value, and function):
      g <- .local_size_gradient_modified(nuisance = x, ...)
      gx <- function(x) .local_size_gradient_modified(nuisance = x, ...)

      # Hessian:
      B <- numDeriv::hessian(func = fx, x)

      return(list(value = f, gradient = g, hessian = B))

    }

    # Use this + the trust-region method to find the maximum size as a function
    # of the nuisance parameter:

    result <- trust::trust(function(x) objfun(x, .gamma0 = gamma0, .odds_ratio,
                                              .m, .n, .df, .alpha, .precision),
                           start, .precision, 1/.precision, minimize = FALSE)


    size <- result$value

    # SAS code has following, but not needed here - we get the
    # resulting value (size):

    #xopt <- result$value
    #size <- local_size_modified(xopt, .gamma0 = gamma0, .odds_ratio,
    #                        .m, .n, .df, .alpha, .precision)

  } else {

    # Else, use the zoom method as per SAS macro:

    res <- rep(0, .maze-1)
    pt <- 0
    gamma0 <- .c[[1]]
    maxat <- 0.5

    # Rejection matrix depends only on (.df, gamma0): build once, reuse on grid
    reject_matrix <- .build_rejection_matrix(.df, gamma0, .m, .n)

    for(j in 1:.zoom_iter){

      for(i in 1:(.maze-1)){

        pt <- maxat + (i-.maze/2)/(.maze^j)

        # New version of fn, using a single rejection matrix
        # rather than building a new one each time.
        res[[i]] <- local_size_modified(pt, .gamma0 = gamma0, .odds_ratio, .m, .n, .df,
                                    .alpha, .precision,
                                    .rejection_matrix = reject_matrix)

      }

      i <- which.max(res)

      old <- maxat
      maxat <- old + (i-.maze/2)/(.maze^j)

    }

    size <- max(res)

  } # End of zoom method

  return(size)

} # End of function
